### ISSUE TITLE
Update based on Primer theme updates

### ISSUE THREAD

**Issue by mrpritchett** [godaddy/wp-activation-theme#3]
Probably going to need to check fonts and color schemes.

**Comment by frankiejarrett** [comment]
@mrpritchett Here are filters in Primer that child themes should use:

## Colors

[`(array) primer_colors`](https://github.com/godaddy/wp-primer-theme/blob/2bb4dd6ce9c6b0a6bdbd9e4cddc0831992097da4/inc/customizer/colors.php#L35) - Register the name, default values, and CSS targets of color areas.

[`(array) primer_color_schemes`](https://github.com/godaddy/wp-primer-theme/blob/2bb4dd6ce9c6b0a6bdbd9e4cddc0831992097da4/inc/customizer/colors.php#L161) - Define a color scheme users can select from that changes the entire palette of available colors. Typically a child theme should always have it's own set of color schemes and should not use default schemes from Primer.

## Fonts

[`(array) primer_font_types`](https://github.com/godaddy/wp-primer-theme/blob/2bb4dd6ce9c6b0a6bdbd9e4cddc0831992097da4/inc/customizer/fonts.php#L72) - Here you can set what the default font should be for each type of font, and what the CSS targets.

[`(array) primer_fonts`](https://github.com/godaddy/wp-primer-theme/blob/2bb4dd6ce9c6b0a6bdbd9e4cddc0831992097da4/inc/customizer/fonts.php#L35) - This is really only here for posterity. If a new font needed for any official child theme it would be better for us to just add it to Primer directly.

## Layouts

[`(array) primer_layouts`](https://github.com/godaddy/wp-primer-theme/blob/2bb4dd6ce9c6b0a6bdbd9e4cddc0831992097da4/inc/customizer/layouts.php#L38) - All available page layouts are exposed in this filter, however, it should be used only for _removing_ layouts that don't apply to a child theme, rather than adding new ones.

[`(string) primer_default_layout`](https://github.com/godaddy/wp-primer-theme/blob/2bb4dd6ce9c6b0a6bdbd9e4cddc0831992097da4/inc/customizer/layouts.php#L63) - Use this to change the default layout, which is set to [`two-column-default`](https://github.com/godaddy/wp-primer-theme/blob/2bb4dd6ce9c6b0a6bdbd9e4cddc0831992097da4/inc/customizer/layouts.php#L17) otherwise.

**Comment by mrpritchett** [comment]
These all appear to be good excepting https://github.com/godaddy/wp-primer-theme/issues/52

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;I7sCt8sM&#x2F;19-activation-fitness-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Activation (Fitness Theme)</a>
